import { Plus, RefreshCw, Trash2 } from "lucide-react";
import { useState } from "react";
import { Badge, Button, Card, CardContent, Empty, ErrorState, Input, Loading, Page, api, date, money, useApi, type FinanceData } from "@trust-deeds/client";

export default function Streams() {
  const query = useApi<FinanceData>(["finance"], "/api/ui/finance");
  const [adding, setAdding] = useState(false);
  const [busy, setBusy] = useState(false);
  const add = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { await api("/api/streams", { method: "POST", body: JSON.stringify({ name: form.get("name"), kind: form.get("kind"), schedule_amount: Number(form.get("amount")), schedule_frequency: form.get("frequency"), due_day: form.get("due_day") ? Number(form.get("due_day")) : null, start_date: new Date().toISOString().slice(0,10) }) }); setAdding(false); await query.refetch(); } finally { setBusy(false); } };
  return <Page title="Streams" description="Recurring and one-off income sources that drive the cash timeline." actions={<><Button variant="outline" size="icon" onClick={() => query.refetch()}><RefreshCw className="size-4" /></Button><Button onClick={() => setAdding(!adding)}><Plus className="size-4" />New stream</Button></>}>{adding ? <Card><CardContent className="pt-5"><form onSubmit={add} className="grid gap-3 md:grid-cols-5"><Input name="name" placeholder="Stream name" required /><select name="kind" className="h-9 rounded-md border bg-background px-3 text-sm"><option value="manual_income">Income</option><option value="manual_expense">Expense</option></select><Input name="amount" type="number" step="0.01" placeholder="Amount" required /><select name="frequency" className="h-9 rounded-md border bg-background px-3 text-sm"><option value="monthly">Monthly</option><option value="weekly">Weekly</option><option value="one_time">One time</option></select><div className="flex gap-2"><Input name="due_day" type="number" min="1" max="31" placeholder="Day" /><Button type="submit" disabled={busy}>{busy ? "Saving…" : "Add"}</Button></div></form></CardContent></Card> : null}{query.isLoading ? <Loading /> : query.error ? <ErrorState error={query.error} /> : !query.data?.streams.length ? <Empty title="No streams" description="Create an income or expense stream to start forecasting." /> : <div className="space-y-3">{query.data.streams.map(stream => <Card key={stream.id}><CardContent className="grid gap-4 pt-5 md:grid-cols-[minmax(0,1fr)_repeat(3,140px)_auto] md:items-center"><div><div className="flex items-center gap-2"><h2 className="font-medium">{stream.name}</h2><Badge>{stream.kind.replaceAll("_", " ")}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{stream.description || `${stream.schedules.length} active schedule${stream.schedules.length === 1 ? "" : "s"}`}</p></div><Datum label="Amount" value={money(stream.schedule_amount)} /><Datum label="Frequency" value={stream.schedule_frequency?.replaceAll("_", " ") || "—"} /><Datum label="Starts" value={date(stream.schedules[0]?.start_date)} /><Button size="icon" variant="ghost" aria-label="Delete stream" onClick={async () => { if (confirm(`Delete ${stream.name}?`)) { await api(`/api/streams/${stream.id}`, { method: "DELETE" }); query.refetch(); } }}><Trash2 className="size-4 text-destructive" /></Button></CardContent></Card>)}</div>}</Page>;
}
function Datum({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium capitalize">{value}</p></div>; }
