// Generated by `nextrs cron generate` from nextrs.toml — do not edit.
// This Worker is a trigger, not a runtime: it only fetches the app's cron
// routes on Vercel. Delete it and you lose nothing but the schedule.
const ROUTES = {
  "0 * * * *": [
    "/internal/cron"
  ]
};

export default {
  async scheduled(event, env, ctx) {
    const paths = ROUTES[event.cron] ?? [];
    ctx.waitUntil(Promise.all(paths.map(async (path) => {
      const response = await fetch(env.APP_URL + path, {
        headers: { Authorization: `Bearer ${env.CRON_SECRET}` },
      });
      console.log(`${event.cron} ${path} -> ${response.status}`);
    })));
  },
};
