import { Play, ShieldCheck } from "lucide-react";
import { Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Empty, IntegrationBoundary, Page, dateTime } from "@trust-deeds/client";
import { useState } from "react";

export default function Sync() { return <IntegrationBoundary>{(data, slug) => <SyncView data={data} slug={slug} />}</IntegrationBoundary>; }

function SyncView({ data, slug }: { data: import("@/types").IntegrationData; slug: string }) {
  const [running, setRunning] = useState(false);
  const run = async () => { setRunning(true); try { await fetch(`/integrations/${encodeURIComponent(slug)}/sync/run`, { method: "POST", credentials: "same-origin", headers: { "Sec-Fetch-Site": "same-origin" } }); window.location.reload(); } finally { setRunning(false); } };
  return <Page title="Sync" description="Provider refresh history and operational controls." actions={<Button onClick={run} disabled={running || data.control.mode !== "enabled"}><Play className="size-4" />{running ? "Starting…" : "Run sync"}</Button>}><section className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardDescription>Write mode</CardDescription><CardTitle className="capitalize">{data.control.mode.replaceAll("_", " ")}</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Scheduler</CardDescription><CardTitle>{data.control.scheduler_enabled ? "Enabled" : "Paused"}</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Cadence</CardDescription><CardTitle className="capitalize">{data.connection.sync_cadence.replaceAll("_", " ")}</CardTitle></CardHeader></Card></section>{data.control.mode !== "enabled" ? <div className="flex gap-3 rounded-xl border bg-muted p-4 text-sm text-muted-foreground"><ShieldCheck className="size-5 shrink-0" />This imported database is intentionally read-only. Enable writes during the final cutover before running provider syncs.</div> : null}{data.sync_logs.length === 0 ? <Empty title="No sync history" description="The first execution will appear here." /> : <Card className="overflow-x-auto"><table className="data-table"><thead><tr><th>Started</th><th>Status</th><th>Loans</th><th>Events</th><th>Snapshots</th><th>Error</th></tr></thead><tbody>{data.sync_logs.map(log => <tr key={log.id}><td>{dateTime(log.started_at)}</td><td><Badge>{log.status}</Badge></td><td>{log.loans_upserted.toLocaleString()}</td><td>{log.events_upserted.toLocaleString()}</td><td>{log.snapshots_created.toLocaleString()}</td><td className="max-w-sm text-xs text-muted-foreground">{log.error_message || "—"}</td></tr>)}</tbody></table></Card>}</Page>;
}
